import type { NextPage } from 'next'
import { useState, useEffect } from 'react';
import { createSpendingRecord } from '../firebase/spendingRecords'
import { signIn, signOut } from '../firebase/authentication'
import { auth, db } from '../firebase/config'
import { onAuthStateChanged, User } from 'firebase/auth'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { collection, query, where, orderBy } from "firebase/firestore";
import useFetchCollectionData from '../hooks/useFetchCollectionData'
import { format } from 'date-fns'

const Home: NextPage = () => {
  const [user, setUser] = useState<User | null>()


  const uid = "shum4q84tFOdAfORInn6QRXRUbt2"
  const q = query(collection(db, "spendingRecords"), where('uid', '==', uid), orderBy('date', 'asc'))

  const [ result, loading, error ] = useFetchCollectionData(q)

  useEffect(() => {
    const unsub = onAuthStateChanged(auth, user => {
      if(user) {
        setUser(user)
      } else {
        setUser(null)
      }
    })

    return () => {
      unsub()
    }
  }, []);

  if(error) {
    return <h1>Error</h1>
  }

  if(loading) {
    return <h1>Loading</h1>
  }

  if(!user) {
    return (
      <>
        <h1>Need to signin</h1> 
        <button onClick={() => {signIn()}}>SignIN</button>
      </>
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={() => {createSpendingRecord({category: "Groceries", amount: 233, uid: user.uid})}}>Create Record</button>
        <button onClick={() => {signIn()}}>SignIN</button>
        <button onClick={() => {signOut()}}>SignOut</button>

        <ul>
          {result.map((item, i) => (
            <li key={i}>
              <span>category: { item.category }</span>
              <span>amount: { item.amount }</span>
              {/* <span>date: { format(new Date(item.date?.toDate()), 'yyyy-MM-dd') }</span> */}
            </li>
          ))}
        </ul>
      </main>


      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
