import type { NextPage } from 'next'
import { useState, useEffect } from 'react';
import { createSpendingRecord, getSpendingRecords } from '../firebase/spendingRecords'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { SpendingRecord } from '../types';

const Home: NextPage = () => {
  const [spendingRecords, setSpendingRecords] = useState<SpendingRecord[]>([]);
  
  useEffect(() => {
    (async() => {
      try {
        const records = await getSpendingRecords()
        setSpendingRecords(records as SpendingRecord[]) // Fix it later
      } catch (e) {
        alert('Ooops')
      }
    })()
  }, []);
 
  console.log(spendingRecords)


  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>


        <button onClick={() => {createSpendingRecord({category: "Groceries", amount: 233})}}>Create</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
